---
- name: Create domain configuration directory
  file: 
    path=/srv/www/sites/{{ inventory_hostname }}
    state=directory
    owner=root
  tags: core

- name: Copy .env
  template:
    src: .env.j2
    dest: /srv/www/sites/{{ inventory_hostname }}/.env

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /srv/www/sites/{{ inventory_hostname }}/docker-compose.yml


- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /srv/www/sites/{{ inventory_hostname }}/Dockerfile

- name: Start site docker container
  command: docker-compose up -d
  args:
    chdir: /srv/www/sites/{{ inventory_hostname }}